import type { Metadata } from "next";
import { Hanken_Grotesk, Caveat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { SITE, SOCIAL } from "../lib/site";
import { Analytics } from "./components/Analytics";

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-display-fam",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-hand-fam",
  display: "swap",
  weight: ["500", "600", "700"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  display: "swap",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.title,
    template: "%s — Yovany Luis",
  },
  description: SITE.description,
  applicationName: "yovany.dev",
  authors: [{ name: SITE.name, url: SITE.url }],
  creator: SITE.name,
  keywords: [
    "AI engineer",
    "production AI",
    "RAG",
    "AI consultant",
    "fractional engineer",
    "LLM features",
    "SaaS",
    "Yovany Luis",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE.url,
    siteName: "yovany.dev",
    title: SITE.title,
    description: SITE.description,
    locale: "en_US",
    // Share image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.title,
    description: SITE.description,
    creator: "@yovanylg",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": `${SITE.url}/#person`,
      name: SITE.name,
      jobTitle: "Senior Software Engineer & Independent AI Consultant",
      url: SITE.url,
      email: `mailto:${SITE.email}`,
      address: {
        "@type": "PostalAddress",
        addressRegion: "Jalisco",
        addressCountry: "MX",
      },
      sameAs: [SOCIAL.linkedin, SOCIAL.github, SOCIAL.x],
      knowsAbout: [
        "Production AI systems",
        "Retrieval-Augmented Generation",
        "LLM evaluation and observability",
        "Web performance",
        "Full-stack engineering",
      ],
    },
    {
      "@type": "ProfessionalService",
      "@id": `${SITE.url}/#service`,
      name: "Yovany Luis — AI Product Engineering",
      description: SITE.description,
      url: SITE.url,
      provider: { "@id": `${SITE.url}/#person` },
      areaServed: "Worldwide",
      serviceType: [
        "AI feature development",
        "AI architecture review",
        "Fractional senior engineering",
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${hanken.variable} ${caveat.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        {/* Set `js` class before paint so scroll-reveals only hide when JS runs. */}
        <script
          dangerouslySetInnerHTML={{
            __html: "document.documentElement.classList.add('js')",
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
